### ISSUE TITLE
[BUG] incompatible version error on attempting to connect to any world

### ISSUE THREAD

**Issue by Beethoven-n** [gameboycjp/KarIO.PDF#2]
i think it has something to do with how the AppVersiuon gets set to `$AppVersion+KarIOPDF.dll`, but when i open the game with this library, it shows everyone as being on a different version, even though my dash says i'm on their version. and when i try to connect to any world, it gives me an incompatible version error.

**Comment by gameboycjp** [comment]
Plugins are intended to add functionality/components. If you try to have a client use something from them and they don't have the same plug in it would crash.
https://discord.com/channels/1040316820650991766/1179507078272909382/1179519705648726057
